version: '2.1'

services:
  api-gateway:
    build: api-gateway/
    mem_limit: 512m
    ports:
      -8085:8085
  checkout-service:
    build: checkout-service/
    mem_limit: 512m
    ports:
      -8082:8080
  config-server:
    build: config-server/
    mem_limit: 512m
    ports:
      -8888:8888
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
      -8761:8761
  notification-service:
    build: notification-service/
    mem_limit: 512m
    ports:
      -8088:8080
  payment-service:
    build: payment-service/
    mem_limit: 512m
    ports:
      -8099:8080
  product-service:
    build: product-service/
    mem_limit: 512m
    ports:
      -8083:8080

