server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          label: main
          uri: git@github.com:EFFM00/config_server_private.git
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKQIBAAKCAgEA1oZ0zHrmBubODnX3hwbNAGuZeA9v59kgFjJUShs9BIudl9i+
            afa0bzTG/P0IV4OUbQcG+lHPNDh5QSWhHuZZV9Hoy29iXwzDGAe0Nkvueybc2nB+
            9Oko+dDGnIr25tSEQnZ6H3U4QhMT5h714u21fuMKCh7ShZ1tqhlxMzKJ1CB8giXU
            jK3kUcDrFka0g77wPeDQdozkCedtTqyJosSv/Un2RhmIAkriEwOrvAjkAYeCspx2
            CMC0qur4KjBYTf/L0dTS/BxGvNBxvEyPgAbWXyuA4yVuT+XrWDegIQYbxWU8Ukkw
            jIdB4oNpLP4TawDgNTjRW2kBGItcMMsgTAd8AbGQlek2u2H5Sz/LajGPIhFCYY7W
            DYJNKyq2kcM8mQfRL+N5ENpCjyiXZDMAozhPxTzTcg5wf4VhO24CFdrzaXL1LJol
            HT9fsoTpzdCtrmAuR16ts2EG+wMi7wyuBXydv6UFDgolVSKTe2vmKfnp8fGgVO2E
            mKGj+Uz2wACBN7UaPkEoxDsqXWNW4CJqj07DKzDzOJdkLhJOv/YLXPfTNtGdRBTb
            EVXRFb2PafwxO8h6VWR9ICVUeOPyTnaBBjQRLn8HFqMUHQ1++iNpa8BJ8wWgrdJB
            MNmztU03KS4mMVLTgr3Md6MHylS1xBZFH6H+ik/VQO62fSflH8++hy8G3HECAwEA
            AQKCAgACSkTqrmiwe+wI9jwuXDWZyqxEnniRu20G46Jn+J64AtQLvA/7UluGgOQb
            bQmW4pQV7mBmEXPCcVRlDEVqLqgXQonHSzD8Bgc6pVFoj3q0JJvwtoj6bRdHhHGs
            V+TvHadsTLa8yXvwY6L/nsa99Y7tk/emWEIj1ESIj3U4iFJ1meOuYYBBgLU6ZLJ1
            xks0yVfn9zOOgm5IR0jQ0VF2U/5zeCPJh4n+yUUc0hoWG6uwcv2Dkd1GNmVvWisM
            S0AUFBYdTzXx5EzihOCj85bIFXqaIT0i36JL9s7CfjSGybmH687fK4IZy/NZe1Dm
            /q7fIm8iTlEY1lgBRrKVIEP/38gUeQrAB6o3D43BVzsjxFIjN040y4+IyZscwToc
            UGB04o9HYjI+xCqwhUSz6kaAeMZ3Jgry2xKlyTGYY7Kpa+jAiywzlKj+5E0Rn4vl
            6BB7yH/Sw2NKnkW3o5PmTu1SFNDJyvPJJjzOmYzmhjodpzgrjjttWNH15UeWtq1g
            Err1AkzCZw8plbUSmALinbCcS/++HtuygTxT0NeF8V5XZDjrBsNLg4GeUNjyRp8g
            cPThQHyymf4r7ZAn1uVWURnpSbrCyBZWZ+AZRQu8LXwGvhO7A6YD8Cq7n7fWUbH8
            tbTgchZlZuxdmhdFKEXzjEx3ttlCaVhNcS2ZfMRE9YdUJDs4QQKCAQEA8qE/35d3
            OV5EatNt8BApyeqKMv9zyX6lXyURa32+UbzxZt9vG8yV5afS1Ltz927cSt4LK7FA
            n+ot8DJPmJ6mh8/BMnku0E1dBoKZLN8h/ZJlpZAaK6L36xI7lJbcEBPbIgNq5aTq
            9oCTq1Gfbq4DN8mE/dWQif2T/toO6wNtFTcDKPQA6TrbWYViw1WAwAKoEkUOF4TG
            CJUOU27KnFXx0h4l9Qcu35WVwSrJx8bzM2b5/tr9fEQMevVBlpiQYnWSvl13GBUS
            B4B0ARfcTV9g63/t3uT0wPz3FmzWVB9tiCJbet8QfzAQSN0TJAEfVK2q1hs9kLy6
            JtcZRx673AiSIQKCAQEA4li81/9TnId9NXwUa5xSFbMB73Q55MCrRLAtVNtA+iuA
            Ch1T1lpHZhKsf9PA4DWxGFf123kuB/MoR1FmdMNgA1gBYylISyKlCXysoF70rQhe
            mq3m8O8i3bA74T4VHKKNSpTsuk/mUEyCQclpzziJ6FydcQ7Gga2f+234K0w27nXL
            mqEcd4VgEcjYIqt/IF6tzY+GgTb6M/SXva0r1VyFYLYKTPghC4T1AbBM7f9FG+6Y
            qbrdAX4MnT/ASOL3ZBdfnaywtWT8yp+gK6qH3Tkd1SSbHCR219MiGH2b01zV03C2
            FAnjkL9wqlZa9Rh/tL2uiuRO19qwtjlB7kmmzXygUQKCAQEA8cCheBPfg5Xd7eMF
            I7G3Ma00TmQh5p79/7NbjBMaUy9ECRCQEM7kfJOfir/MaLpZXW+pCbvvfGdFppM6
            pANQQvpKshP1BTBQhHAUV5VstM/t3+2ZZelXxS3Bl+hJFOvz6AwnsvGD/GFYwdbu
            WMWiBzAQByuIfTXhBIoZWylqwzyxNVkKn1k5vhUdtyu2wZrkBHAx/lUZTOvX/mHi
            F6u663WGtIKXvce6E2Ki8x/Uq17rsXhaIjtbhBhjZb5V/wTPVkaip6g28qqW64/u
            vllOpNgvF2xiQvjK6dlAJUm7RW2WYPNp6JDnaPJ+Y92KbkEse3FhAppJkPG6Chch
            b7hKgQKCAQAd+ZBwrmB9PzgmqBrwMVBxjTY5ZtPv5lAIFai7LxoIx0/6hu2+WlBQ
            RTLQ7tMBHjsotSVa/k5JQTtZTn9aATGq37G3VxU61gizG+6kgk62x3/3zgXibFja
            sOcNKjKTizdY5CYBemlOwwMRAUJg7eTdf75d5Y4GSF8CZgrSeRJhO/pNrP5fGaui
            T03IMZvxRniP22z9mbFCxiZ+OPuwEsObDiCJFucRZncn1RgrAH4/d7aB67wu4Wl8
            PaASRvRqLeo8sEzqiMgtcTw97CR3+INp4aIk9PNEG7LNOX00XXv3t1p1huW7Go8q
            D6uV/7uRzPjbbea/ETgLucNwchKD7fgxAoIBAQCibuNeAwmf87NdvoOiFLVriOK7
            1A7BhDvOSjWE33mvhiZByeRyh0ecw+RnS8MU5iRukKQa/RzMDQQOUUlgl3yKCk9K
            lAauzO3E4QMe19osEj6WKDk4aFJOyD0IuJr9qsTbVYot0OkFny6fNmE7S5lqMoSf
            YX9FNQleuFkCFejPGYRQ0g2Hivbv+k9EOByA1cY4cchBnj4b00i/WumeQXI2nbYo
            0N5pKQ+LoXsZ/WzXbKYJD1Xi7Iyt499I4BP1HbmlAsY92rJ16RXzdhuQmxbxRva8
            QWDBwZN/qPIgxU+GmLtjC7UWw4qwhR+u+xyqpsIJGt14j5A40pxtc+J4BCZa
            -----END RSA PRIVATE KEY-----
