server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          label: main
          uri: git@github.com:EFFM00/config_server_private.git
          hostKeyAlgorithm: ssh-rsa
          privateKey: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKQIBAAKCAgEAzpfUnL3L2vNcj+Bf2G9ZSeMso+rak49N1LEdUeqTXyN8kRLh
            KWVG9lZsUwVGk2YFofFLPeLglC0gM9LakJngctWlBDFm7WVNbvKfU2tcRWi1VjYm
            tXNzqsUWHzjOv++eK0y4wBnw6mZdwLl6eYtbDmHmGAVfV8vzLTuavaoinkZPtQHw
            M+utmmFvgcVxPgIv59rvVAamlQkw8XrMWCjpSlwN/n/cjW+1zm2X01U0Htcr0I2m
            ygYqx2wY98uXVW09xZ6bGA7AbzEtmIFMXQk8D+q/+S4Nm/7pHFROgmRabVbdVEi2
            pAM48Sem+m0404mQLHSoNiKmwi6yI1E4TRMsXYZ9flrBo0emof+dI9buiT3feN0p
            Y+Cbrh5uNPOEi2C1WUtYhve9RjXNESOGc0sLkAQctCURzmclA/V+ydK4lCR832Qr
            Ka9hyUXyFOyX9ZgK9C8EC20U+zNps9vhijfY8wpyHUe8sO6GiadCOMiGX8wMdVeO
            GhoQtwLMynvYyzK8CaD8RNv84AWoLm128Eq0sXCbMRMrkhijdlE+XQvuCuLvWEmy
            nBYa+ma4b6Xh2qNJ0tjXPOd5aktiZUwPLB3hYfDOvW/6MdY86wpbRP70KiuF3NFX
            QyeTwXmoXO8YXjZPMvXZbBmiYzn7/X5HSLkQiBt+ReuWEKfGQeqDMSCITDUCAwEA
            AQKCAgArwXOaCQbapk2V+X9DT34ZTKDBTPYjZ6gj4qljlqvE7DavYVDIHDe15+ME
            iGsEwAh0Xq9BecJ4D8CwyTlahATKPZ64LyBuKlUGqSN+nxAJcV5q1ohHSR8X7as8
            TKNZeo5E/Hhq03O3qZu0vHQIty+/cZOyxbyGU197VpL1FcpEPH8YRsNRs9puhrF/
            ykosSHlOAYxL/yacDTjNBGWwTGXwxmN+YiVb3Wujv4l3DKY/2/HfN4k6Y6j+2NHG
            9dtlEACT0P5nT4SJaGCQWt5KHDEY6+7h/1OJlSlZQy/npQqT+uBgwA/S2A3g4bWX
            d7ef8hRTnhecc6VfHlXDbinfBS8RdDmt99VB4kDE4VdcpT5/KR70A6hBih4OfzhG
            zWnGWGmjV2vPdUU9lOPhxrQgx7P2m2WUF2jrzRluaix7ZNW0jr2K5r2Hy14wjV8c
            L1u2aZ3Tc3vbx0KK+D63l+Pj0SLaBM/MYBNFhJgjIaBP4fk3fp5oNbHg3U0lWNP2
            Ly8c3Mh2oLkewPn+8fOxK2VtPio0y6yDcBGGI+0R/ISlVXxZpYV3DFSXWqVe6Oh8
            VpKBHRln9WIjsOobfkINNBzk/UtA9n4qfO4mRFpMclXB+YUYO4+1KIqz7Pljbj83
            8gycLiwEQNMRhLqDiILHirvibVeekGTc7roKtBb7uHv/fSRb5wKCAQEA+MCYQeEN
            5n1HRR7Ln7KGMsXJSdgAVlQKjHcuXf2BGCyC8dMMJzYXbxV+8xpdtxTHSgLs/vGi
            BDrZ5WUKafFEl4T2y5Ql2rUuanrWRV/tgUA+/qZPRwDlZb4zmB7hiBkNcJi1aCVt
            daXSIip+68E16J8TzLzIN7NnJ0v8XiToFAGzBQuvPX4APEIhAZLjb6Az0FwDqki8
            8uVsTppstjgdAhqqUFz8gpcVnK4qonAkrdxPXYBGUMKI2Uwerf+9mycJhYWqlw2x
            Bp9GJPVhx4PpsOjHymwBFe46nfOZqf9Z88OqUn1Vsy2z4rrQ7xZtxDzV7ag0USKD
            bYM/4JkeErRmFwKCAQEA1JzGyirCAKVRSJfs67wcR9c5Nu5mn1vLkXidtCRFuzk2
            rVe5e5y3wp+VKogJALy1zDL/x1+yZzBxDs1fl2HuSFSVLoZQZjpQcoMaRlIMxHwj
            hPDQbL8kHCa4/mocDp41JwaPcguOGHj/amW0FZwu/a7SCMhdV+Sp1TCdOHepBqwJ
            jN3+g0AfcbVM5FKfnYlF/pPnMfaNvuiimRZ965z0azBsd7thRVu23FQTEYAxxlnv
            ZYBPttY5+acJaSw6j+RO2g103vFnyJsvh9we7img4N0MUTg/4640vzMRKzY1OKWM
            ln+4+JSICb3UjGXnbdAlvlbsygajEjDKJbtXCsTbkwKCAQEAkxVWMgX/sRy8antm
            DVyDCzx148rrkCALSLkj2oGNtpyDJLgUxI6wVoeQU/BwH1QS7olCVxDLKtMdig0v
            lisJ0snVH9TOeT6OXnmZftXU2osBdJMj5yj5eyp22WjRFCc0EjLJePZAfcL5uCgG
            eiH5XT3KeFHb1UuoH81HQOdzrni+wKoDCUoam4bCe2q+Pn+sg3QU2rg9uSW839Fh
            nHEbfeYEdJY23IS3S7iUDw5eMctFxlSVvyT3w/zFWz8PftEbSS8bCkwXM4Iz+KB7
            G3y9TlSl5ePs1GnTkRe78Y/CQWedqz7e0J6icdritaw+ZT1PhUHjBWJx8ewcdhIz
            fP3cKwKCAQEAnufGE9e9Q+pLRCx4oP/pSzBqzMmF3dkn3sP9amQp0fLDEO+d6+uH
            1GidfjpKMEjav5HmZcb6efFUrrGEnopNI7ZEAY/Vi3JOKigefSxZ6oi1q2io/n4l
            qPywC0aXTb2lEFPw5lYIj/XvQEBfRj+DR4tf47yNN2HqJTK+bzPQGvJ9+ND6pnJI
            jh3pKEUwkvfEXq+AfnE+I8+Pp0eOOYkHjQ2WJC7iVopjs20LC2t6yDrzmDM8YPTg
            Q906RWcPJfiHjqW8EdzvqpmB/tLgMzTdzvKngBTAe5T6S2UJkfhj8sCYwOsY/oFU
            46MDtyN6wzJs40Poml43hyL8ExNfzOaxDQKCAQByVjyZqYJHQ2G1pZXQT9wwMxQV
            XIi8XWxSoeJkCATqLb1pqsyKzRgIreUgsxIODOJLk/Z9B4KzLhzzR5iXn694gre+
            OOGKMVxI1LC6eTZ00mQ99uo+i5Q4E82gGgSOUHbvQyJiudOkQIdsSHAvruFdgRnT
            0KxAaPAPKDrmHgE2fyC+lBYWiDeDcVn7ArS0f78+22MTCJ2s3xRoTKzrpYtghcZI
            jJqkDSkV9fkND/rwGJXt8r7TnVSqLCSthX/sg2uidWh2yDiq4B8pFfjdc0hSjcOU
            kBU0nwRYiKN5a3/Vo+8E6ZA9U2/zap+lAM8pLUu2QKf84k7qwMqWmgbzh+F0
            -----END RSA PRIVATE KEY-----
