server:
  port: 8093

spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  cloud:
    config:
      importCheck:
        enable: false
      enabled: false
      discovery:
        serviceId: config-server
        enabled: false
    gateway:
      routes:
        - id: checkout-service
          uri: lb://checkout-service
          predicates:
            - Path=/checkout
